/* eslint-disable */
// Generated by scripts/generate-types.mjs — do not edit.
// Source of truth: schema/*.json. Run `npm run types:generate`.

// ── schema/bundled/aura-response.bundle.json ──

/**
 * One header cell — the definition of a column. A *data cell* names its source with `field` or `fields`; a *grouping cell* has neither and spans several columns with `colspan` > 1. Unknown keys are dropped, except `data-*` attributes, which are kept and rendered onto the `<th>`.
 */
export type HeaderCell = FieldAndFieldsAreMutuallyExclusive &
    FieldsRequiresAnExplicitKey &
    ACellWithoutFieldFieldsMustBeAGroupingCell & {
        /**
         * Column heading text. Required on every cell; `null` renders an empty heading.
         */
        content: string | null;
        /**
         * Unique column identifier — the key `body.columnConfigs` entries are looked up by, and the key used in session persistence. Defaults to `field` when only `field` is given; required when `fields` is used.
         */
        key?: string | null;
        /**
         * Item field this column reads. Mutually exclusive with `fields`. Required on data cells (a grouping cell — one with `colspan` > 1 and no field — may omit it).
         */
        field?: string | null;
        fields?: Fields;
        /**
         * Alternative heading text, kept for backwards compatibility.
         */
        label?: string | null;
        colspan?: Colspan;
        rowspan?: Rowspan;
        width?: CssSize;
        /**
         * Allow the user to drag the column width.
         */
        resizable?: boolean | null;
        pad?: Pad;
        padStart?: Pad;
        padEnd?: Pad;
        chars?: Chars;
        /**
         * Offer sorting on this column. Sorting is server-side: the field lands in the request’s `sortable` array.
         */
        sortable?: boolean | null;
        /**
         * Offer the per-column search input. Server-side: the field lands in the request’s `searchable` array.
         */
        searchable?: boolean | null;
        /**
         * Offer the per-column filter dropdown. Server-side: the field lands in the request’s `filterable` array.
         */
        filterable?: boolean | null;
        elements?: FilterElements;
        /**
         * Render row-selection checkboxes in this column. The chosen ids are sent as `selected`.
         */
        selectable?: boolean | null;
        /**
         * Initial column visibility.
         */
        show?: boolean | null;
        /**
         * Offer a range (min–max) search instead of a term search. Sends `min` / `max` in the request’s `searchable` entry.
         */
        between?: boolean | null;
        reference?: Reference;
        align?: Align;
        /**
         * Heading text colour.
         */
        color?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | string
            | string
            | null;
        /**
         * Heading background colour.
         */
        background?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | string
            | string
            | null;
        size?: Size;
        fontSize?: FontSize;
        fontWeight?: FontWeight;
        /**
         * Italic heading text.
         */
        italic?: boolean | null;
        /**
         * Reset italics (`font-style: normal`).
         */
        normal?: boolean | null;
        lineHeight?: LineHeight;
        /**
         * Monospace heading font.
         */
        monospace?: boolean | null;
        text?: TextUtility;
        /**
         * Format the column’s values as numbers.
         */
        number?: boolean | null;
        /**
         * Format the column’s values as currency, using the host app’s `currencyCode` config.
         */
        currency?: boolean | null;
        /**
         * Format the column’s values with `Intl.NumberFormat` unit style.
         */
        unit?:
            | (
                  | 'acre'
                  | 'bit'
                  | 'byte'
                  | 'celsius'
                  | 'centimeter'
                  | 'day'
                  | 'degree'
                  | 'fahrenheit'
                  | 'fluid-ounce'
                  | 'foot'
                  | 'gallon'
                  | 'gigabit'
                  | 'gigabyte'
                  | 'gram'
                  | 'hectare'
                  | 'hour'
                  | 'inch'
                  | 'kilobit'
                  | 'kilobyte'
                  | 'kilogram'
                  | 'kilometer'
                  | 'liter'
                  | 'megabit'
                  | 'megabyte'
                  | 'meter'
                  | 'microsecond'
                  | 'mile'
                  | 'mile-scandinavian'
                  | 'milliliter'
                  | 'millimeter'
                  | 'millisecond'
                  | 'minute'
                  | 'month'
                  | 'nanosecond'
                  | 'ounce'
                  | 'percent'
                  | 'petabyte'
                  | 'pound'
                  | 'second'
                  | 'stone'
                  | 'terabit'
                  | 'terabyte'
                  | 'week'
                  | 'yard'
                  | 'year'
              )
            | null;
        /**
         * Format the column’s values as dates.
         */
        date?: boolean | null;
        /**
         * Format the column’s values as date + time.
         */
        datetime?: boolean | null;
        /**
         * Format the column’s values as phone numbers.
         */
        phone?: boolean | null;
        /**
         * Read the column’s values as seconds and render them as `HH:mm:ss`. Integers only; negatives allowed.
         */
        time?: boolean | null;
        slice?: Slice;
        /**
         * Upper-case the rendered values.
         */
        uppercase?: boolean | null;
        /**
         * Lower-case the rendered values.
         */
        lowercase?: boolean | null;
        /**
         * Capitalise the first letter of the rendered values.
         */
        capitalize?: boolean | null;
        /**
         * Treat the column’s values as objects.
         */
        object?: boolean | null;
        /**
         * Render the column’s values as raw HTML. Sanitised before rendering.
         */
        raw?: boolean | null;
        /**
         * CSS classes on the heading cell.
         */
        class?: string | [string, ...string[]] | null;
        /**
         * Inline CSS on the heading cell.
         */
        style?: string | null;
        type?: CellType;
        [k: string]: any;
    } & {
        /**
         * Column heading text. Required on every cell; `null` renders an empty heading.
         */
        content: string | null;
        /**
         * Unique column identifier — the key `body.columnConfigs` entries are looked up by, and the key used in session persistence. Defaults to `field` when only `field` is given; required when `fields` is used.
         */
        key?: string | null;
        /**
         * Item field this column reads. Mutually exclusive with `fields`. Required on data cells (a grouping cell — one with `colspan` > 1 and no field — may omit it).
         */
        field?: string | null;
        fields?: Fields;
        /**
         * Alternative heading text, kept for backwards compatibility.
         */
        label?: string | null;
        colspan?: Colspan;
        rowspan?: Rowspan;
        width?: CssSize;
        /**
         * Allow the user to drag the column width.
         */
        resizable?: boolean | null;
        pad?: Pad;
        padStart?: Pad;
        padEnd?: Pad;
        chars?: Chars;
        /**
         * Offer sorting on this column. Sorting is server-side: the field lands in the request’s `sortable` array.
         */
        sortable?: boolean | null;
        /**
         * Offer the per-column search input. Server-side: the field lands in the request’s `searchable` array.
         */
        searchable?: boolean | null;
        /**
         * Offer the per-column filter dropdown. Server-side: the field lands in the request’s `filterable` array.
         */
        filterable?: boolean | null;
        elements?: FilterElements;
        /**
         * Render row-selection checkboxes in this column. The chosen ids are sent as `selected`.
         */
        selectable?: boolean | null;
        /**
         * Initial column visibility.
         */
        show?: boolean | null;
        /**
         * Offer a range (min–max) search instead of a term search. Sends `min` / `max` in the request’s `searchable` entry.
         */
        between?: boolean | null;
        reference?: Reference;
        align?: Align;
        /**
         * Heading text colour.
         */
        color?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | string
            | string
            | null;
        /**
         * Heading background colour.
         */
        background?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | string
            | string
            | null;
        size?: Size;
        fontSize?: FontSize;
        fontWeight?: FontWeight;
        /**
         * Italic heading text.
         */
        italic?: boolean | null;
        /**
         * Reset italics (`font-style: normal`).
         */
        normal?: boolean | null;
        lineHeight?: LineHeight;
        /**
         * Monospace heading font.
         */
        monospace?: boolean | null;
        text?: TextUtility;
        /**
         * Format the column’s values as numbers.
         */
        number?: boolean | null;
        /**
         * Format the column’s values as currency, using the host app’s `currencyCode` config.
         */
        currency?: boolean | null;
        /**
         * Format the column’s values with `Intl.NumberFormat` unit style.
         */
        unit?:
            | (
                  | 'acre'
                  | 'bit'
                  | 'byte'
                  | 'celsius'
                  | 'centimeter'
                  | 'day'
                  | 'degree'
                  | 'fahrenheit'
                  | 'fluid-ounce'
                  | 'foot'
                  | 'gallon'
                  | 'gigabit'
                  | 'gigabyte'
                  | 'gram'
                  | 'hectare'
                  | 'hour'
                  | 'inch'
                  | 'kilobit'
                  | 'kilobyte'
                  | 'kilogram'
                  | 'kilometer'
                  | 'liter'
                  | 'megabit'
                  | 'megabyte'
                  | 'meter'
                  | 'microsecond'
                  | 'mile'
                  | 'mile-scandinavian'
                  | 'milliliter'
                  | 'millimeter'
                  | 'millisecond'
                  | 'minute'
                  | 'month'
                  | 'nanosecond'
                  | 'ounce'
                  | 'percent'
                  | 'petabyte'
                  | 'pound'
                  | 'second'
                  | 'stone'
                  | 'terabit'
                  | 'terabyte'
                  | 'week'
                  | 'yard'
                  | 'year'
              )
            | null;
        /**
         * Format the column’s values as dates.
         */
        date?: boolean | null;
        /**
         * Format the column’s values as date + time.
         */
        datetime?: boolean | null;
        /**
         * Format the column’s values as phone numbers.
         */
        phone?: boolean | null;
        /**
         * Read the column’s values as seconds and render them as `HH:mm:ss`. Integers only; negatives allowed.
         */
        time?: boolean | null;
        slice?: Slice;
        /**
         * Upper-case the rendered values.
         */
        uppercase?: boolean | null;
        /**
         * Lower-case the rendered values.
         */
        lowercase?: boolean | null;
        /**
         * Capitalise the first letter of the rendered values.
         */
        capitalize?: boolean | null;
        /**
         * Treat the column’s values as objects.
         */
        object?: boolean | null;
        /**
         * Render the column’s values as raw HTML. Sanitised before rendering.
         */
        raw?: boolean | null;
        /**
         * CSS classes on the heading cell.
         */
        class?: string | [string, ...string[]] | null;
        /**
         * Inline CSS on the heading cell.
         */
        style?: string | null;
        type?: CellType;
        [k: string]: any;
    };
/**
 * Field names for a multi-field column (at least one, max 100 chars each). Mutually exclusive with `field`; requires an explicit `key`.
 */
export type Fields = [string, ...string[]] | null;
/**
 * Number of columns the cell spans (1–50).
 */
export type Colspan = number | null;
/**
 * Number of rows the cell spans (1–20).
 */
export type Rowspan = number | null;
/**
 * CSS length: `'100px'`, `'50%'`, `'2.5rem'` or `'auto'`. Used for both `width` and `height`.
 */
export type CssSize = string | null;
/**
 * Padding length in characters for `padStart` / `padEnd` (0–100).
 */
export type Pad = number | null;
/**
 * Character(s) used by `padStart` / `padEnd` (max 10 chars).
 */
export type Chars = string | null;
/**
 * Options offered by the column filter: either an array of strings/numbers, or an object of `value: label` pairs. When omitted, Aura derives the options from the loaded rows.
 */
export type FilterElements =
    | [string | number, ...(string | number)[]]
    | {
          [k: string]: string | number;
      }
    | null;
/**
 * Name of the field whose value is sent to the server for sorting/searching instead of this column’s own field (max 100 chars).
 */
export type Reference = string | null;
/**
 * Text alignment inside the cell.
 */
export type Align = ('start' | 'center' | 'end') | null;
/**
 * Size variant.
 */
export type Size = ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
/**
 * CSS font-size: a `px`/`rem`/`em`/`%` length, or a keyword (`small`, `large`, `x-large`, …).
 */
export type FontSize = string | null;
/**
 * CSS font-weight: a multiple of 100 between 100 and 900 (number or string), or `normal` / `bold` / `lighter` / `bolder`.
 */
export type FontWeight = number | string | null;
/**
 * CSS line-height: a positive number, a `px`/`em`/`rem`/`%` length, or `normal`.
 */
export type LineHeight = string | number | null;
/**
 * Bootstrap text utility class; must start with `text-` (e.g. `text-truncate`).
 */
export type TextUtility = string | null;
/**
 * Truncate the rendered text to this many characters (1–10000).
 */
export type Slice = number | null;
/**
 * Cell type marker on a header cell. Formatting types (`number`, `currency`, `date`, `datetime`, `phone`, `time`) format the value; the rest name a `body.columnConfigs` renderer.
 */
export type CellType =
    | (
          | 'number'
          | 'currency'
          | 'date'
          | 'datetime'
          | 'phone'
          | 'time'
          | 'static'
          | 'icon'
          | 'link'
          | 'modal'
          | 'reference'
          | 'badge'
          | 'progress'
          | 'button'
          | 'custom'
      )
    | null;
/**
 * Value of a `data-*` attribute (max 1000 chars). HTML-sanitised on arrival.
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 *
 * This interface was referenced by `undefined`'s JSON-Schema definition
 * via the `patternProperty` "^data-".
 */
export type DataAttributeValue = string | null;
/**
 * One column renderer. `type` selects which renderer — and which config shape — applies.
 */
export type ColumnConfig =
    | StaticConfig
    | IconConfig
    | LinkConfig
    | ModalConfig
    | BadgeConfig
    | ProgressConfig
    | ButtonConfig
    | ReferenceConfig
    | CustomConfig;
/**
 * Static text cell. Renders `value` (or the branch that matched) through the shared formatter chain: number / currency / date / phone / unit formatting, then case transforms, slicing and padding.
 */
export type StaticConfig = ValueIsRequiredUnlessIfOrElseBranchesAreGiven & {
    /**
     * Discriminator. Selects the static renderer.
     */
    type: 'static';
    /**
     * The text to render.
     */
    value?: string | null;
    /**
     * Text colour of the rendered content.
     */
    color?:
        | ('primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark' | 'light')
        | null;
    /**
     * Background colour behind the rendered content.
     */
    background?:
        | ('primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark' | 'light')
        | string
        | null;
    /**
     * Text alignment inside the cell.
     */
    align?: ('start' | 'center' | 'end') | null;
    /**
     * CSS font-size: a `px`/`rem`/`em`/`%` length, or a keyword (`small`, `large`, `x-large`, …).
     */
    fontSize?: string | null;
    /**
     * CSS font-weight: a multiple of 100 between 100 and 900 (number or string), or `normal` / `bold` / `lighter` / `bolder`.
     */
    fontWeight?: number | string | null;
    /**
     * Italic text.
     */
    italic?: boolean | null;
    /**
     * Reset italics (`font-style: normal`).
     */
    normal?: boolean | null;
    /**
     * CSS line-height: a positive number, a `px`/`em`/`rem`/`%` length, or `normal`.
     */
    lineHeight?: string | number | null;
    /**
     * Bootstrap text utility class; must start with `text-` (e.g. `text-truncate`).
     */
    text?: string | null;
    /**
     * Upper-case the rendered text.
     */
    uppercase?: boolean | null;
    /**
     * Lower-case the rendered text.
     */
    lowercase?: boolean | null;
    /**
     * Capitalise the first letter of the rendered text.
     */
    capitalize?: boolean | null;
    /**
     * Monospace font.
     */
    monospace?: boolean | null;
    /**
     * Truncate the rendered text to this many characters (1–10000).
     */
    slice?: number | null;
    /**
     * Format the value as a number.
     */
    number?: boolean | null;
    /**
     * Format the value as currency, using the host app’s `currencyCode` config.
     */
    currency?: boolean | null;
    /**
     * Format the value as a date.
     */
    date?: boolean | null;
    /**
     * Format the value as a phone number.
     */
    phone?: boolean | null;
    /**
     * Unit appended to the formatted value.
     */
    unit?: string | null;
    /**
     * Padding length in characters for `padStart` / `padEnd` (0–100).
     */
    padStart?: number | null;
    /**
     * Padding length in characters for `padStart` / `padEnd` (0–100).
     */
    padEnd?: number | null;
    /**
     * Character(s) used by `padStart` / `padEnd` (max 10 chars).
     */
    chars?: string | null;
    /**
     * CSS classes on the rendered element.
     */
    class?: string | [string, ...string[]] | null;
    /**
     * Inline CSS on the rendered element.
     */
    style?: string | null;
    /**
     * Conditional styling for the `<td>` around the content.
     */
    cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
    /**
     * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
     */
    key?: string | null;
    /**
     * Condition branches; the first matching one is merged over this config.
     */
    if?: ConditionalRule[] | null;
    /**
     * Config merged in when no `if` branch matched.
     */
    else?: {
        [k: string]: any;
    } | null;
    [k: string]: any;
};
export type ValueIsRequiredUnlessIfOrElseBranchesAreGiven = {
    [k: string]: any;
};
/**
 * Icon cell. `icon` and `variant` / `color` are registry keys — the preprocessor resolves them against the host app’s `icons` and `variants` config into the `class` array before rendering. Given a `route`, the glyph is wrapped in a link.
 */
export type IconConfig = OneOfIconClassOrMappingIsRequiredUnlessIfOrElseBranchesAreGiven & {
    /**
     * Discriminator. Selects the icon renderer.
     */
    type: 'icon';
    /**
     * Key into the host app’s `icons` config registry; resolved into CSS classes.
     */
    icon?: string | null;
    /**
     * CSS classes on the `<i>` element. Accepted directly instead of `icon`.
     */
    class?: string | [string, ...string[]] | null;
    /**
     * Key into the host app’s `variants` config registry, or a Bootstrap colour name; resolved into a `text-{colour}` class. CSS colour syntax is rejected here.
     */
    variant?: string | null;
    /**
     * Alternative to `variant`, resolved the same way.
     */
    color?: string | null;
    /**
     * Size variant.
     */
    size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
    /**
     * Accessible label, rendered as `aria-label`.
     */
    alt?: string | null;
    /**
     * Tooltip text, rendered as `title`.
     */
    title?: string | null;
    /**
     * URL template; `{key}` placeholders are filled from the row, dots become slashes, and the host app’s `siteName` is prepended.
     */
    route?: string | null;
    /**
     * Inline CSS on the `<i>` element.
     */
    style?: string | null;
    /**
     * Value → icon config lookup, applied after the `if` / `else` branches are flattened.
     */
    mapping?: {
        [k: string]: IconMappingEntry;
    } | null;
    /**
     * Conditional styling for the `<td>` around the icon.
     */
    cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
    /**
     * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
     */
    key?: string | null;
    /**
     * Condition branches; the first matching one is merged over this config.
     */
    if?: ConditionalRule[] | null;
    /**
     * Config merged in when no `if` branch matched.
     */
    else?: {
        [k: string]: any;
    } | null;
    [k: string]: any;
};
export type OneOfIconClassOrMappingIsRequiredUnlessIfOrElseBranchesAreGiven = {
    [k: string]: any;
};
/**
 * CSS class names: one string (max 500 chars) or an array of class names (max 50 items, 100 chars each). HTML-sanitised on arrival.
 */
export type CssClass = string | [string, ...string[]] | null;
/**
 * Anchor cell. The text comes from `field` (per row), `value` (fixed) or a `mapping` entry; the URL from `route`.
 */
export type LinkConfig = OneOfFieldValueRouteOrMappingIsRequiredUnlessIfOrElseBranchesAreGiven & {
    /**
     * Discriminator. Selects the link renderer.
     */
    type: 'link';
    /**
     * Item field whose value becomes the link text.
     */
    field?: string | null;
    /**
     * Fixed link text, used instead of `field`.
     */
    value?: string | null;
    /**
     * URL template; `{key}` placeholders are filled from the row, dots become slashes, and the host app’s `siteName` is prepended.
     */
    route?: string | null;
    /**
     * Anchor `target` attribute.
     */
    target?: ('_blank' | '_self' | '_parent' | '_top') | null;
    /**
     * Anchor `rel` attribute.
     */
    rel?: string | null;
    /**
     * Tooltip text, rendered as `title`.
     */
    title?: string | null;
    /**
     * Text colour of the rendered content.
     */
    color?:
        | ('primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark' | 'light')
        | string
        | null;
    /**
     * Key into the host app’s `variants` config registry, or a Bootstrap colour name.
     */
    variant?: string | null;
    /**
     * Text alignment inside the cell.
     */
    align?: ('start' | 'center' | 'end') | null;
    /**
     * CSS font-size: a `px`/`rem`/`em`/`%` length, or a keyword (`small`, `large`, `x-large`, …).
     */
    fontSize?: string | null;
    /**
     * CSS font-weight: a multiple of 100 between 100 and 900 (number or string), or `normal` / `bold` / `lighter` / `bolder`.
     */
    fontWeight?: number | string | null;
    /**
     * Italic text.
     */
    italic?: boolean | null;
    /**
     * CSS line-height: a positive number, a `px`/`em`/`rem`/`%` length, or `normal`.
     */
    lineHeight?: string | number | null;
    /**
     * Bootstrap text utility class; must start with `text-` (e.g. `text-truncate`).
     */
    text?: string | null;
    /**
     * Upper-case the rendered text.
     */
    uppercase?: boolean | null;
    /**
     * Lower-case the rendered text.
     */
    lowercase?: boolean | null;
    /**
     * Capitalise the first letter of the rendered text.
     */
    capitalize?: boolean | null;
    /**
     * Monospace font.
     */
    monospace?: boolean | null;
    /**
     * Truncate the rendered text to this many characters (1–10000).
     */
    slice?: number | null;
    /**
     * Format the value as currency, using the host app’s `currencyCode` config.
     */
    currency?: boolean | null;
    /**
     * Format the value as a date.
     */
    date?: boolean | null;
    /**
     * Format the value as a phone number.
     */
    phone?: boolean | null;
    /**
     * Unit appended to the formatted value.
     */
    unit?: string | null;
    /**
     * CSS class names: one string (max 500 chars) or an array of class names (max 50 items, 100 chars each). HTML-sanitised on arrival.
     */
    class?: string | [string, ...string[]] | null;
    /**
     * Inline CSS on the rendered element.
     */
    style?: string | null;
    /**
     * Value → link config lookup (variant, colour, route, target …), selected by `field`.
     */
    mapping?: {
        [k: string]: LinkMappingEntry;
    } | null;
    /**
     * Conditional styling for the `<td>` around the link.
     */
    cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
    /**
     * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
     */
    key?: string | null;
    /**
     * Condition branches; the first matching one is merged over this config.
     */
    if?: ConditionalRule[] | null;
    /**
     * Config merged in when no `if` branch matched.
     */
    else?: {
        [k: string]: any;
    } | null;
    [k: string]: any;
};
export type OneOfFieldValueRouteOrMappingIsRequiredUnlessIfOrElseBranchesAreGiven = {
    [k: string]: any;
};
/**
 * Bootstrap theme colour name, or a CSS colour (`#fff`, `#ffffff`, `rgb(…)`, `rgba(…)`, or a CSS colour keyword). Used for both `color` and `background`.
 */
export type Color =
    | ('primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark' | 'light')
    | string
    | null;
/**
 * Modal trigger cell. `id` names the modal to open; the trigger is either the nested `content` config, or the `icon` / `button` shorthand the preprocessor expands into one. `destroyModal` is the built-in delete-confirmation modal.
 */
export type ModalConfig = IdIsRequiredUnlessIfOrElseBranchesAreGiven &
    OneOfIconButtonOrContentIsRequiredUnlessIfOrElseBranchesAreGiven & {
        /**
         * Discriminator. Selects the modal renderer.
         */
        type: 'modal';
        /**
         * Identifier of the modal to open. `destroyModal` opens Aura’s built-in delete confirmation.
         */
        id?: string | null;
        /**
         * URL the modal submits to; `{key}` placeholders are filled from the row.
         */
        route?: string | null;
        /**
         * Nested column config rendering the trigger — any column type.
         */
        content?: {
            [k: string]: any;
        } | null;
        /**
         * Icon-trigger shorthand: a key into the host app’s `icons` config registry. Normalised into `content`.
         */
        icon?: string | null;
        /**
         * Key into the host app’s `variants` config registry, or a Bootstrap colour name. CSS colour syntax is rejected here.
         */
        variant?: string | null;
        /**
         * Button-trigger shorthand: the button variant. Normalised into `content`.
         */
        button?: string | null;
        /**
         * Text of the button shorthand.
         */
        value?: string | null;
        /**
         * Size variant.
         */
        size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
        /**
         * Anchor `target` attribute for a link trigger.
         */
        target?: ('_blank' | '_self' | '_parent' | '_top') | null;
        /**
         * CSS class names: one string (max 500 chars) or an array of class names (max 50 items, 100 chars each). HTML-sanitised on arrival.
         */
        class?: string | [string, ...string[]] | null;
        /**
         * Inline CSS on the trigger.
         */
        style?: string | null;
        /**
         * Accessible label on the trigger.
         */
        alt?: string | null;
        /**
         * Tooltip text on the trigger.
         */
        title?: string | null;
        /**
         * Conditional styling for the `<td>` around the trigger.
         */
        cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
        /**
         * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
         */
        key?: string | null;
        /**
         * Condition branches; the first matching one is merged over this config.
         */
        if?: ConditionalRule[] | null;
        /**
         * Config merged in when no `if` branch matched.
         */
        else?: {
            [k: string]: any;
        } | null;
        [k: string]: any;
    };
export type IdIsRequiredUnlessIfOrElseBranchesAreGiven = {
    [k: string]: any;
};
export type OneOfIconButtonOrContentIsRequiredUnlessIfOrElseBranchesAreGiven = {
    [k: string]: any;
};
/**
 * Bootstrap badge cell. Label and colour resolve in one of three modes: static (`value` / `field` with a fixed `variant`), value → config `mapping`, or boolean `trueValue` / `falseValue`. In counter mode `prefix` / `suffix`, `maxValue` (overflow renders `{maxValue}{suffix}`) and `showZero` apply.
 */
export type BadgeConfig =
    OneOfFieldValueMappingTrueValueOrFalseValueIsRequiredUnlessIfOrElseBranchesAreGiven & {
        /**
         * Discriminator. Selects the badge renderer.
         */
        type: 'badge';
        /**
         * Item field whose value drives the badge.
         */
        field?: string | null;
        /**
         * Fixed label text, used instead of `field`.
         */
        value?: string | null;
        /**
         * Base Bootstrap colour, rendered as `text-bg-{variant}`.
         */
        variant?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | null;
        /**
         * Render as a pill (`rounded-pill`).
         */
        pill?: boolean | null;
        /**
         * Size variant.
         */
        size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
        /**
         * Value → badge config lookup, keyed by the resolved value.
         */
        mapping?: {
            [k: string]: BadgeMappingEntry;
        } | null;
        /**
         * Badge config used when the value is truthy.
         */
        trueValue?: BadgeMappingEntry | null;
        /**
         * Badge config used when the value is falsy.
         */
        falseValue?: BadgeMappingEntry | null;
        /**
         * Render the badge when the numeric value is 0. Defaults to `true`.
         */
        showZero?: boolean | null;
        /**
         * Cap on the displayed number; above it the badge renders `{maxValue}{suffix}`.
         */
        maxValue?: number | null;
        /**
         * Overflow marker appended past `maxValue`, e.g. `+`.
         */
        suffix?: string | null;
        /**
         * Text prepended to the label, e.g. `#`.
         */
        prefix?: string | null;
        /**
         * Key into the host app’s `icons` config registry, rendered as an `<i>` glyph.
         */
        icon?: string | null;
        /**
         * Icon placement relative to the label.
         */
        iconPosition?: ('start' | 'end') | null;
        /**
         * Bootstrap 5 theme colour name.
         */
        color?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | null;
        /**
         * Bootstrap theme colour name, or a CSS colour (`#fff`, `#ffffff`, `rgb(…)`, `rgba(…)`, or a CSS colour keyword). Used for both `color` and `background`.
         */
        background?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | null;
        /**
         * Text alignment inside the cell.
         */
        align?: ('start' | 'center' | 'end') | null;
        /**
         * CSS font-size: a `px`/`rem`/`em`/`%` length, or a keyword (`small`, `large`, `x-large`, …).
         */
        fontSize?: string | null;
        /**
         * CSS font-weight: a multiple of 100 between 100 and 900 (number or string), or `normal` / `bold` / `lighter` / `bolder`.
         */
        fontWeight?: number | string | null;
        /**
         * Italic text.
         */
        italic?: boolean | null;
        /**
         * Reset italics (`font-style: normal`).
         */
        normal?: boolean | null;
        /**
         * CSS line-height: a positive number, a `px`/`em`/`rem`/`%` length, or `normal`.
         */
        lineHeight?: string | number | null;
        /**
         * Bootstrap text utility class; must start with `text-` (e.g. `text-truncate`).
         */
        text?: string | null;
        /**
         * Upper-case the rendered text.
         */
        uppercase?: boolean | null;
        /**
         * Lower-case the rendered text.
         */
        lowercase?: boolean | null;
        /**
         * Capitalise the first letter of the rendered text.
         */
        capitalize?: boolean | null;
        /**
         * Monospace font.
         */
        monospace?: boolean | null;
        /**
         * Truncate the rendered text to this many characters (1–10000).
         */
        slice?: number | null;
        /**
         * Format the value as a number.
         */
        number?: boolean | null;
        /**
         * Format the value as currency, using the host app’s `currencyCode` config.
         */
        currency?: boolean | null;
        /**
         * Format the value as a date.
         */
        date?: boolean | null;
        /**
         * Format the value as a phone number.
         */
        phone?: boolean | null;
        /**
         * Unit appended to the formatted value.
         */
        unit?: string | null;
        /**
         * Padding length in characters for `padStart` / `padEnd` (0–100).
         */
        padStart?: number | null;
        /**
         * Padding length in characters for `padStart` / `padEnd` (0–100).
         */
        padEnd?: number | null;
        /**
         * Character(s) used by `padStart` / `padEnd` (max 10 chars).
         */
        chars?: string | null;
        /**
         * CSS class names: one string (max 500 chars) or an array of class names (max 50 items, 100 chars each). HTML-sanitised on arrival.
         */
        class?: string | [string, ...string[]] | null;
        /**
         * Inline CSS on the rendered element.
         */
        style?: string | null;
        /**
         * Conditional styling for the `<td>` around the badge.
         */
        cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
        /**
         * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
         */
        key?: string | null;
        /**
         * Condition branches; the first matching one is merged over this config.
         */
        if?: ConditionalRule[] | null;
        /**
         * Config merged in when no `if` branch matched.
         */
        else?: {
            [k: string]: any;
        } | null;
        [k: string]: any;
    };
export type OneOfFieldValueMappingTrueValueOrFalseValueIsRequiredUnlessIfOrElseBranchesAreGiven = {
    [k: string]: any;
};
/**
 * Bootstrap 5 theme colour name.
 */
export type BootstrapColor =
    ('primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark' | 'light') | null;
/**
 * Bootstrap progress bar. The value comes from `field` or `value` and is scaled against `min` / `max`; the bar colour comes from `variant`, a value `mapping`, or a `thresholds` range table. With `stacked` the `bars` array renders several segments in one track.
 */
export type ProgressConfig =
    OneOfFieldValueOrStackedWithBarsIsRequiredUnlessIfOrElseBranchesAreGiven & {
        /**
         * Discriminator. Selects the progress renderer.
         */
        type: 'progress';
        /**
         * Item field holding the numeric value.
         */
        field?: string | null;
        /**
         * Fixed numeric value, used instead of `field`.
         */
        value?: number | null;
        /**
         * Upper bound of the scale: a number, or the name of the item field holding it. Defaults to 100.
         */
        max?: number | string | null;
        /**
         * Lower bound of the scale. Defaults to 0.
         */
        min?: number | null;
        /**
         * Bootstrap 5 theme colour name.
         */
        variant?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | null;
        /**
         * Track height, e.g. `20px`.
         */
        height?: string | null;
        /**
         * Striped bar.
         */
        striped?: boolean | null;
        /**
         * Animate the stripes.
         */
        animated?: boolean | null;
        /**
         * Bar label: `true` for the value itself, or fixed text.
         */
        label?: boolean | string | null;
        /**
         * Render the label inside the bar or next to it.
         */
        labelPosition?: ('inside' | 'outside') | null;
        /**
         * Value → bar config lookup, keyed by the resolved value.
         */
        mapping?: {
            [k: string]: ProgressMappingEntry;
        } | null;
        /**
         * Bootstrap colour → `[min, max]` range. The first range containing the value sets the bar colour.
         */
        thresholds?: {
            [k: string]: any[];
        } | null;
        /**
         * Render the `bars` entries as segments of one track.
         */
        stacked?: boolean | null;
        /**
         * Segments of a stacked bar.
         */
        bars?: [ProgressBar, ...ProgressBar[]] | null;
        /**
         * Show the raw value in the label.
         */
        showValue?: boolean | null;
        /**
         * Show the percentage in the label.
         */
        showPercent?: boolean | null;
        /**
         * Decimal places in the label (0–20).
         */
        decimals?: number | null;
        /**
         * Text appended to the label.
         */
        suffix?: string | null;
        /**
         * Text prepended to the label.
         */
        prefix?: string | null;
        /**
         * Bootstrap 5 theme colour name.
         */
        color?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | null;
        /**
         * Bootstrap theme colour name, or a CSS colour (`#fff`, `#ffffff`, `rgb(…)`, `rgba(…)`, or a CSS colour keyword). Used for both `color` and `background`.
         */
        background?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | null;
        /**
         * Text alignment inside the cell.
         */
        align?: ('start' | 'center' | 'end') | null;
        /**
         * CSS font-size: a `px`/`rem`/`em`/`%` length, or a keyword (`small`, `large`, `x-large`, …).
         */
        fontSize?: string | null;
        /**
         * CSS font-weight: a multiple of 100 between 100 and 900 (number or string), or `normal` / `bold` / `lighter` / `bolder`.
         */
        fontWeight?: number | string | null;
        /**
         * Italic text.
         */
        italic?: boolean | null;
        /**
         * CSS line-height: a positive number, a `px`/`em`/`rem`/`%` length, or `normal`.
         */
        lineHeight?: string | number | null;
        /**
         * Bootstrap text utility class; must start with `text-` (e.g. `text-truncate`).
         */
        text?: string | null;
        /**
         * Monospace font.
         */
        monospace?: boolean | null;
        /**
         * CSS class names: one string (max 500 chars) or an array of class names (max 50 items, 100 chars each). HTML-sanitised on arrival.
         */
        class?: string | [string, ...string[]] | null;
        /**
         * Inline CSS on the rendered element.
         */
        style?: string | null;
        /**
         * Conditional styling for the `<td>` around the bar.
         */
        cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
        /**
         * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
         */
        key?: string | null;
        /**
         * Condition branches; the first matching one is merged over this config.
         */
        if?: ConditionalRule[] | null;
        /**
         * Config merged in when no `if` branch matched.
         */
        else?: {
            [k: string]: any;
        } | null;
        [k: string]: any;
    };
export type OneOfFieldValueOrStackedWithBarsIsRequiredUnlessIfOrElseBranchesAreGiven =
    | {
          [k: string]: any;
      }
    | {
          stacked: true;
          [k: string]: any;
      };
/**
 * Button cell. The label comes from `field`, `value` or a `mapping` entry; with `route` the button acts as a link.
 */
export type ButtonConfig =
    OneOfFieldValueRouteIconOrMappingIsRequiredUnlessIfOrElseBranchesAreGiven & {
        /**
         * Discriminator. Selects the button renderer.
         */
        type: 'button';
        /**
         * Item field whose value becomes the button label.
         */
        field?: string | null;
        /**
         * Fixed button label, used instead of `field`.
         */
        value?: string | null;
        /**
         * URL template; `{key}` placeholders are filled from the row, dots become slashes, and the host app’s `siteName` is prepended.
         */
        route?: string | null;
        /**
         * Key into the host app’s `variants` config registry, or a Bootstrap colour name.
         */
        variant?: string | null;
        /**
         * Size variant.
         */
        size?: ('xs' | 'sm' | 'md' | 'lg' | 'xl') | null;
        /**
         * Rounded corners.
         */
        rounded?: boolean | null;
        /**
         * Pill-shaped button (`rounded-pill`).
         */
        pill?: boolean | null;
        /**
         * Key into the host app’s `icons` config registry, rendered as an `<i>` glyph.
         */
        icon?: string | null;
        /**
         * Icon placement relative to the label.
         */
        iconPosition?: ('start' | 'end') | null;
        /**
         * Render the button disabled.
         */
        disabled?: boolean | null;
        /**
         * Tooltip text, rendered as `title`.
         */
        title?: string | null;
        /**
         * The `type` attribute of the `<button>` element.
         */
        htmlType?: ('button' | 'submit' | 'reset') | null;
        /**
         * Bootstrap 5 theme colour name.
         */
        color?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | null;
        /**
         * Bootstrap theme colour name, or a CSS colour (`#fff`, `#ffffff`, `rgb(…)`, `rgba(…)`, or a CSS colour keyword). Used for both `color` and `background`.
         */
        background?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | null;
        /**
         * Text alignment inside the cell.
         */
        align?: ('start' | 'center' | 'end') | null;
        /**
         * CSS font-size: a `px`/`rem`/`em`/`%` length, or a keyword (`small`, `large`, `x-large`, …).
         */
        fontSize?: string | null;
        /**
         * CSS font-weight: a multiple of 100 between 100 and 900 (number or string), or `normal` / `bold` / `lighter` / `bolder`.
         */
        fontWeight?: number | string | null;
        /**
         * Italic text.
         */
        italic?: boolean | null;
        /**
         * Reset italics (`font-style: normal`).
         */
        normal?: boolean | null;
        /**
         * CSS line-height: a positive number, a `px`/`em`/`rem`/`%` length, or `normal`.
         */
        lineHeight?: string | number | null;
        /**
         * Bootstrap text utility class; must start with `text-` (e.g. `text-truncate`).
         */
        text?: string | null;
        /**
         * Upper-case the rendered text.
         */
        uppercase?: boolean | null;
        /**
         * Lower-case the rendered text.
         */
        lowercase?: boolean | null;
        /**
         * Capitalise the first letter of the rendered text.
         */
        capitalize?: boolean | null;
        /**
         * Monospace font.
         */
        monospace?: boolean | null;
        /**
         * Truncate the rendered text to this many characters (1–10000).
         */
        slice?: number | null;
        /**
         * Format the value as a number.
         */
        number?: boolean | null;
        /**
         * Format the value as currency, using the host app’s `currencyCode` config.
         */
        currency?: boolean | null;
        /**
         * Format the value as a date.
         */
        date?: boolean | null;
        /**
         * Format the value as a phone number.
         */
        phone?: boolean | null;
        /**
         * Unit appended to the formatted value.
         */
        unit?: string | null;
        /**
         * Padding length in characters for `padStart` / `padEnd` (0–100).
         */
        padStart?: number | null;
        /**
         * Padding length in characters for `padStart` / `padEnd` (0–100).
         */
        padEnd?: number | null;
        /**
         * Character(s) used by `padStart` / `padEnd` (max 10 chars).
         */
        chars?: string | null;
        /**
         * CSS class names: one string (max 500 chars) or an array of class names (max 50 items, 100 chars each). HTML-sanitised on arrival.
         */
        class?: string | [string, ...string[]] | null;
        /**
         * Inline CSS on the rendered element.
         */
        style?: string | null;
        /**
         * Conditional styling for the `<td>` around the button.
         */
        cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
        /**
         * Value → button config lookup (variant, size, disabled, icon …), selected by `field`.
         */
        mapping?: {
            [k: string]: ButtonMappingEntry;
        } | null;
        /**
         * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
         */
        key?: string | null;
        /**
         * Condition branches; the first matching one is merged over this config.
         */
        if?: ConditionalRule[] | null;
        /**
         * Config merged in when no `if` branch matched.
         */
        else?: {
            [k: string]: any;
        } | null;
        [k: string]: any;
    };
export type OneOfFieldValueRouteIconOrMappingIsRequiredUnlessIfOrElseBranchesAreGiven = {
    [k: string]: any;
};
/**
 * Boolean switch. `null` is accepted and read as `false`.
 */
export type Flag = boolean | null;
/**
 * Reference (lookup) cell. Renders one field, several fields joined by `separator`, or the label a `mapping` entry gives for the value — then runs the shared formatter chain over the result.
 */
export type ReferenceConfig =
    OneOfFieldFieldsMappingOrValueIsRequiredUnlessIfOrElseBranchesAreGiven & {
        /**
         * Discriminator. Selects the reference renderer.
         */
        type: 'reference';
        /**
         * Item field holding the value.
         */
        field?: string | null;
        /**
         * Several item fields, rendered joined by `separator`.
         */
        fields?: [string, ...string[]] | null;
        /**
         * Text placed between the `fields` values.
         */
        separator?: string | null;
        /**
         * Fixed text. Takes priority over `fields` and `field`.
         */
        value?: string | null;
        /**
         * Bootstrap 5 theme colour name.
         */
        color?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | null;
        /**
         * Bootstrap theme colour name, or a CSS colour (`#fff`, `#ffffff`, `rgb(…)`, `rgba(…)`, or a CSS colour keyword). Used for both `color` and `background`.
         */
        background?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | null;
        /**
         * Text alignment inside the cell.
         */
        align?: ('start' | 'center' | 'end') | null;
        /**
         * CSS font-size: a `px`/`rem`/`em`/`%` length, or a keyword (`small`, `large`, `x-large`, …).
         */
        fontSize?: string | null;
        /**
         * CSS font-weight: a multiple of 100 between 100 and 900 (number or string), or `normal` / `bold` / `lighter` / `bolder`.
         */
        fontWeight?: number | string | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        italic?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        normal?: boolean | null;
        /**
         * CSS line-height: a positive number, a `px`/`em`/`rem`/`%` length, or `normal`.
         */
        lineHeight?: string | number | null;
        /**
         * Bootstrap text utility class; must start with `text-` (e.g. `text-truncate`).
         */
        text?: string | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        uppercase?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        lowercase?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        capitalize?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        monospace?: boolean | null;
        /**
         * Truncate the rendered text to this many characters (1–10000).
         */
        slice?: number | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        number?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        currency?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        date?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        phone?: boolean | null;
        /**
         * Unit appended to the formatted value.
         */
        unit?: string | null;
        /**
         * Padding length in characters for `padStart` / `padEnd` (0–100).
         */
        padStart?: number | null;
        /**
         * Padding length in characters for `padStart` / `padEnd` (0–100).
         */
        padEnd?: number | null;
        /**
         * Character(s) used by `padStart` / `padEnd` (max 10 chars).
         */
        chars?: string | null;
        /**
         * CSS class names: one string (max 500 chars) or an array of class names (max 50 items, 100 chars each). HTML-sanitised on arrival.
         */
        class?: string | [string, ...string[]] | null;
        /**
         * Inline CSS on the rendered element.
         */
        style?: string | null;
        /**
         * Conditional styling for the `<td>`.
         */
        cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
        /**
         * Value → label + formatting lookup, keyed by the resolved value.
         */
        mapping?: {
            [k: string]: ReferenceMappingEntry;
        } | null;
        /**
         * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
         */
        key?: string | null;
        /**
         * Condition branches; the first matching one is merged over this config.
         */
        if?: ConditionalRule[] | null;
        /**
         * Config merged in when no `if` branch matched.
         */
        else?: {
            [k: string]: any;
        } | null;
        [k: string]: any;
    };
export type OneOfFieldFieldsMappingOrValueIsRequiredUnlessIfOrElseBranchesAreGiven = {
    [k: string]: any;
};
/**
 * Escape hatch. `renderer` and `callback` name functions in the host app’s function registry — the response carries the name only, never code. `template` is an interpolated string. With none of them, the cell falls back to rendering `field` / `fields` / `value`.
 */
export type CustomConfig =
    OneOfRendererCallbackTemplateFieldFieldsOrValueIsRequiredUnlessIfOrElseBranchesAreGiven & {
        /**
         * Discriminator. Selects the custom renderer.
         */
        type: 'custom';
        /**
         * Item field holding the value.
         */
        field?: string | null;
        /**
         * Several item fields passed to the renderer.
         */
        fields?: [string, ...string[]] | null;
        /**
         * Fixed text.
         */
        value?: string | null;
        /**
         * Name of a function in the host app’s function registry that returns the rendered node.
         */
        renderer?: string | null;
        /**
         * Name of a function in the host app’s function registry that returns the text to render.
         */
        callback?: string | null;
        /**
         * Template string; `{placeholder}` tokens are filled from the row and from `params`.
         */
        template?: string | null;
        /**
         * Extra values available to `template` and to the registered functions.
         */
        params?: {
            [k: string]: any;
        } | null;
        /**
         * Value → template-parameter lookup, keyed by the resolved value.
         */
        mapping?: {
            [k: string]: CustomTemplateParams;
        } | null;
        /**
         * Bootstrap 5 theme colour name.
         */
        color?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | null;
        /**
         * Bootstrap theme colour name, or a CSS colour (`#fff`, `#ffffff`, `rgb(…)`, `rgba(…)`, or a CSS colour keyword). Used for both `color` and `background`.
         */
        background?:
            | (
                  | 'primary'
                  | 'secondary'
                  | 'success'
                  | 'danger'
                  | 'warning'
                  | 'info'
                  | 'dark'
                  | 'light'
              )
            | string
            | null;
        /**
         * Text alignment inside the cell.
         */
        align?: ('start' | 'center' | 'end') | null;
        /**
         * CSS font-size: a `px`/`rem`/`em`/`%` length, or a keyword (`small`, `large`, `x-large`, …).
         */
        fontSize?: string | null;
        /**
         * CSS font-weight: a multiple of 100 between 100 and 900 (number or string), or `normal` / `bold` / `lighter` / `bolder`.
         */
        fontWeight?: number | string | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        italic?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        normal?: boolean | null;
        /**
         * CSS line-height: a positive number, a `px`/`em`/`rem`/`%` length, or `normal`.
         */
        lineHeight?: string | number | null;
        /**
         * Bootstrap text utility class; must start with `text-` (e.g. `text-truncate`).
         */
        text?: string | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        uppercase?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        lowercase?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        capitalize?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        monospace?: boolean | null;
        /**
         * Truncate the rendered text to this many characters (1–10000).
         */
        slice?: number | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        number?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        currency?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        date?: boolean | null;
        /**
         * Boolean switch. `null` is accepted and read as `false`.
         */
        phone?: boolean | null;
        /**
         * Unit appended to the formatted value.
         */
        unit?: string | null;
        /**
         * Padding length in characters for `padStart` / `padEnd` (0–100).
         */
        padStart?: number | null;
        /**
         * Padding length in characters for `padStart` / `padEnd` (0–100).
         */
        padEnd?: number | null;
        /**
         * Character(s) used by `padStart` / `padEnd` (max 10 chars).
         */
        chars?: string | null;
        /**
         * CSS class names: one string (max 500 chars) or an array of class names (max 50 items, 100 chars each). HTML-sanitised on arrival.
         */
        class?: string | [string, ...string[]] | null;
        /**
         * Inline CSS on the rendered element.
         */
        style?: string | null;
        /**
         * Conditional styling for the `<td>`.
         */
        cellRules?: (CellFormattingOptions & ConditionalConfig) | null;
        /**
         * Item field the `if` conditions read, and the field substituted into `{key}` placeholders in `route`. Defaults to the column key.
         */
        key?: string | null;
        /**
         * Condition branches; the first matching one is merged over this config.
         */
        if?: ConditionalRule[] | null;
        /**
         * Config merged in when no `if` branch matched.
         */
        else?: {
            [k: string]: any;
        } | null;
        [k: string]: any;
    };
export type OneOfRendererCallbackTemplateFieldFieldsOrValueIsRequiredUnlessIfOrElseBranchesAreGiven =
    {
        [k: string]: any;
    };

/**
 * The JSON one Aura table expects from its endpoint. `header` describes the columns and is required; `items` carries the row data; `body` configures how individual columns render; `meta` / `links` drive the pagination bar. Keys beyond these are ignored.
 */
export interface AuraResponse {
    header: Header;
    body?: Body;
    footer?: Footer;
    /**
     * The rows. Each entry is one row object, read by the `field` / `key` names the header declares; nested values are reachable with dotted field names. Values are rendered as they arrive — no schema is imposed on them.
     */
    items?: any[];
    meta?: Meta;
    links?: Links;
    [k: string]: any;
}
/**
 * Column definitions. Required — without it there is no table to render.
 */
export interface Header {
    /**
     * Header rows, top to bottom. At least one row is required; several rows build a grouped header.
     *
     * @minItems 1
     */
    rows: [HeaderRow, ...HeaderRow[]];
    settings?: HeaderSettings | null;
    [k: string]: any;
}
/**
 * One header row. Keys other than `cells` are dropped.
 */
export interface HeaderRow {
    /**
     * Cells of the row, left to right. At least one is required.
     *
     * @minItems 1
     */
    cells: [HeaderCell, ...HeaderCell[]];
}
export interface FieldAndFieldsAreMutuallyExclusive {
    [k: string]: any;
}
export interface FieldsRequiresAnExplicitKey {
    [k: string]: any;
}
export interface ACellWithoutFieldFieldsMustBeAGroupingCell {
    [k: string]: any;
}
/**
 * Header-wide settings.
 */
export interface HeaderSettings {
    /**
     * Keep the header fixed to the top of the scroll container.
     */
    sticky?: boolean | null;
    /**
     * CSS length: `'100px'`, `'50%'`, `'2.5rem'` or `'auto'`. Used for both `width` and `height`.
     */
    height?: string | null;
    /**
     * Fields the toolbar’s global search covers. Every entry must match the `field` of some header cell — an unknown field is a validation error.
     *
     * @minItems 1
     */
    searchableItems?: [string, ...string[]];
    [k: string]: any;
}
/**
 * Per-column rendering configuration.
 */
export interface Body {
    /**
     * Per-column renderers, keyed by the cell’s `field` rather than by its `key` — a multi-field cell takes one entry per member field. `cellRules` is the single exception: it is read from the entry named by the column’s `key`. An entry whose `type` is not one of the supported renderers is reported as a warning and skipped — the rest of the body still renders.
     */
    columnConfigs?: {
        [k: string]: ColumnConfig;
    } | null;
    /**
     * CSS classes per column, keyed by the header cell’s `key`. Passed through to the cell unvalidated.
     */
    columnStyles?: {
        [k: string]: CssClass;
    } | null;
    settings?: BodySettings | null;
    /**
     * Conditional styling for whole rows: the base formatting merged with the `if` / `else` branches, evaluated per row.
     */
    rowRules?: (CellFormattingOptions & ConditionalConfig) | null;
    [k: string]: any;
}
/**
 * Visual options applied to the `<td>` element itself.
 */
export interface CellFormattingOptions {
    /**
     * Cell background colour.
     */
    background?: string | null;
    /**
     * Cell text colour.
     */
    color?: string | null;
    /**
     * Draw the top border.
     */
    borderTop?: boolean | null;
    /**
     * Draw the bottom border.
     */
    borderBottom?: boolean | null;
    /**
     * Draw the left border.
     */
    borderLeft?: boolean | null;
    /**
     * Draw the right border.
     */
    borderRight?: boolean | null;
    /**
     * Border colour.
     */
    borderColor?: string | null;
    /**
     * Border width, e.g. `3px`.
     */
    borderWidth?: string | null;
    /**
     * Inner padding CSS value, e.g. `8px 16px`.
     */
    padding?: string | null;
    /**
     * Extra CSS classes on the cell.
     */
    class?: string | [string, ...string[]] | null;
    /**
     * Inline CSS on the cell.
     */
    style?: string | null;
    /**
     * Cell opacity, 0–1.
     */
    opacity?: number | null;
    [k: string]: any;
}
/**
 * Conditional rendering. `key` names the item field the conditions read; each `if` branch that matches is merged over the base config, and `else` applies when none matched.
 */
export interface ConditionalConfig {
    /**
     * Item field the conditions are evaluated against. There is no default — without a string `key` the conditions are skipped and the base configuration is applied as it stands.
     */
    key?: string | null;
    /**
     * Condition branches, evaluated in order.
     */
    if?: ConditionalRule[] | null;
    /**
     * Config applied when no `if` branch matched.
     */
    else?: {
        [k: string]: any;
    } | null;
    [k: string]: any;
}
/**
 * One branch of an `if` array. Exactly one operator key decides whether the branch matches — the first recognised operator key wins, in object key order. Every remaining key is the configuration applied when it matches (its shape is the shape of the config the rule sits in).
 */
export interface ConditionalRule {
    /**
     * Strictly equal to the given value (`===`) — no coercion, so `1` and `"1"` never match. A decimal column serialised as a string is compared as a string.
     */
    eq?: {
        [k: string]: any;
    };
    /**
     * Strictly not equal to the given value (`!==`), with the same strictness as `eq`.
     */
    ne?: {
        [k: string]: any;
    };
    /**
     * Alias of `ne`.
     */
    neq?: {
        [k: string]: any;
    };
    /**
     * Greater than the given value. Both sides are read as dates first; failing that both must be numbers — a numeric string such as `"12.50"` makes the comparison silently false.
     */
    gt?: {
        [k: string]: any;
    };
    /**
     * Alias of `gt`.
     */
    bigger?: {
        [k: string]: any;
    };
    /**
     * Greater than or equal to the given value. Dates first, otherwise both sides must be numbers — see `gt`.
     */
    gte?: {
        [k: string]: any;
    };
    /**
     * Alias of `gte`.
     */
    biggerOrEqual?: {
        [k: string]: any;
    };
    /**
     * Less than the given value. Dates first, otherwise both sides must be numbers — see `gt`.
     */
    lt?: {
        [k: string]: any;
    };
    /**
     * Alias of `lt`.
     */
    smaller?: {
        [k: string]: any;
    };
    /**
     * Less than or equal to the given value. Dates first, otherwise both sides must be numbers — see `gt`.
     */
    lte?: {
        [k: string]: any;
    };
    /**
     * Alias of `lte`.
     */
    smallerOrEqual?: {
        [k: string]: any;
    };
    /**
     * Inside the inclusive `[min, max]` range — a two-element array. All three values are read as dates first; failing that all three must be numbers, and anything else is silently false.
     *
     * @minItems 2
     * @maxItems 2
     */
    between?: [any, any];
    /**
     * Contained by the given array, compared strictly — `1` does not match `"1"`.
     */
    in?: any[];
    /**
     * Not contained by the given array, compared strictly — see `in`.
     */
    notIn?: any[];
    /**
     * Substring match.
     */
    contains?: {
        [k: string]: any;
    };
    /**
     * Prefix match.
     */
    startsWith?: {
        [k: string]: any;
    };
    /**
     * Suffix match.
     */
    endsWith?: {
        [k: string]: any;
    };
    /**
     * Matches the given regular expression (source string).
     */
    regex?: {
        [k: string]: any;
    };
    /**
     * Value is exactly `null` — pass `true`. A field missing from the row resolves to `undefined` and does not match.
     */
    null?: {
        [k: string]: any;
    };
    /**
     * Value is anything other than `null` — pass `true`. A field missing from the row resolves to `undefined`, which does match.
     */
    notNull?: {
        [k: string]: any;
    };
    /**
     * Value is `null`, `undefined`, an empty string, `0` or `false` — pass `true`. An empty array or object is not empty.
     */
    empty?: {
        [k: string]: any;
    };
    /**
     * Value is none of `null`, `undefined`, an empty string, `0` or `false` — pass `true`. An empty array or object counts as not empty.
     */
    notEmpty?: {
        [k: string]: any;
    };
    /**
     * Value is exactly `true` — pass `true`. An identity check, not truthiness: `1` and `"yes"` do not match, so a `tinyint` sent as a number never does.
     */
    true?: {
        [k: string]: any;
    };
    /**
     * Value is exactly `false` — pass `true`. Not falsiness: `0`, an empty string and `null` do not match.
     */
    false?: {
        [k: string]: any;
    };
    [k: string]: any;
}
/**
 * One entry of the `mapping` lookup, keyed by the field value.
 */
export interface IconMappingEntry {
    icon?: string | null;
    variant?: string | null;
    color?: string | null;
    class?: CssClass;
    title?: string | null;
    alt?: string | null;
    [k: string]: any;
}
/**
 * One entry of the `mapping` lookup, keyed by the field value.
 */
export interface LinkMappingEntry {
    variant?: string | null;
    color?: Color;
    class?: CssClass;
    title?: string | null;
    route?: string | null;
    target?: ('_blank' | '_self' | '_parent' | '_top') | null;
    rel?: string | null;
    [k: string]: any;
}
/**
 * One badge configuration — used as a `mapping` entry and as `trueValue` / `falseValue`.
 */
export interface BadgeMappingEntry {
    label?: string | null;
    variant?: BootstrapColor;
    icon?: string | null;
    class?: CssClass;
    [k: string]: any;
}
/**
 * One entry of the `mapping` lookup, keyed by the field value.
 */
export interface ProgressMappingEntry {
    variant?: BootstrapColor;
    label?: string | null;
    class?: CssClass;
    [k: string]: any;
}
/**
 * One segment of a stacked progress bar.
 */
export interface ProgressBar {
    /**
     * Item field holding this segment’s value.
     */
    field: string;
    /**
     * Bootstrap 5 theme colour name.
     */
    variant?:
        | ('primary' | 'secondary' | 'success' | 'danger' | 'warning' | 'info' | 'dark' | 'light')
        | null;
    /**
     * Segment label.
     */
    label?: string | null;
    [k: string]: any;
}
/**
 * One entry of the `mapping` lookup, keyed by the field value.
 */
export interface ButtonMappingEntry {
    variant?: string | null;
    color?: BootstrapColor;
    background?: Color;
    size?: Size;
    rounded?: Flag;
    pill?: Flag;
    disabled?: Flag;
    icon?: string | null;
    iconPosition?: ('start' | 'end') | null;
    title?: string | null;
    route?: string | null;
    class?: CssClass;
    [k: string]: any;
}
/**
 * One entry of the `mapping` lookup, keyed by the field value.
 */
export interface ReferenceMappingEntry {
    /**
     * Text rendered for this value.
     */
    label?: string | null;
    color?: BootstrapColor;
    background?: Color;
    align?: Align;
    fontSize?: FontSize;
    fontWeight?: FontWeight;
    italic?: Flag;
    normal?: Flag;
    lineHeight?: LineHeight;
    text?: TextUtility;
    uppercase?: Flag;
    lowercase?: Flag;
    capitalize?: Flag;
    monospace?: Flag;
    slice?: Slice;
    number?: Flag;
    currency?: Flag;
    date?: Flag;
    phone?: Flag;
    unit?: string | null;
    padStart?: Pad;
    padEnd?: Pad;
    chars?: Chars;
    class?: CssClass;
    [k: string]: any;
}
/**
 * Template parameters for one `mapping` entry: `name: value` pairs substituted into `template`.
 */
export interface CustomTemplateParams {
    [k: string]: string | number | boolean | null;
}
/**
 * Body-wide settings.
 */
export interface BodySettings {
    /**
     * Boolean switch. `null` is accepted and read as `false`.
     */
    striped?: boolean | null;
    /**
     * Boolean switch. `null` is accepted and read as `false`.
     */
    hoverable?: boolean | null;
    [k: string]: any;
}
/**
 * Footer rows, built from the same cells as the header.
 */
export interface Footer {
    /**
     * Footer rows, top to bottom. At least one row is required.
     *
     * @minItems 1
     */
    rows: [HeaderRow, ...HeaderRow[]];
    settings?: FooterSettings | null;
    [k: string]: any;
}
/**
 * Footer-wide settings.
 */
export interface FooterSettings {
    /**
     * Boolean switch. `null` is accepted and read as `false`.
     */
    sticky?: boolean | null;
    /**
     * CSS length: `'100px'`, `'50%'`, `'2.5rem'` or `'auto'`. Used for both `width` and `height`.
     */
    height?: string | null;
    [k: string]: any;
}
/**
 * Pagination state.
 */
export interface Meta {
    /**
     * Current page number, 1-based.
     */
    current_page: number;
    /**
     * Index of the first item on the page; `null` on an empty page.
     */
    from?: number | null;
    /**
     * Number of the last page.
     */
    last_page: number;
    /**
     * Base URL of the paginated resource.
     */
    path?: string;
    /**
     * Items per page — the value the request sent as `paginate`.
     */
    per_page: number;
    /**
     * Index of the last item on the page; `null` on an empty page.
     */
    to?: number | null;
    /**
     * Total number of items across all pages.
     */
    total: number;
    [k: string]: any;
}
/**
 * Pagination URLs.
 */
export interface Links {
    /**
     * URL of the first page.
     */
    first?: string | null;
    /**
     * URL of the last page.
     */
    last?: string | null;
    /**
     * URL of the previous page; `null` on the first page.
     */
    prev?: string | null;
    /**
     * URL of the next page; `null` on the last page.
     */
    next?: string | null;
    [k: string]: any;
}

// ── schema/bundled/aura-request.bundle.json ──

/**
 * What Aura sends to the endpoint on every fetch. `POST` / `PUT` / `PATCH` carry it as the JSON body, `GET` / `DELETE` as query parameters (`requestMethod` config, default `POST`). `page` and `paginate` are always present; the rest appear only while the matching feature is active. Sent alongside the `Content-Type: application/json`, `Accept: application/json` and `X-Requested-With: XMLHttpRequest` headers, plus `Authorization: Bearer …` or `X-Site-Token: …` when a `siteToken` is configured.
 */
export interface AuraRequest {
    /**
     * Requested page, 1-based.
     */
    page: number;
    /**
     * Items per page — the page size chosen in the toolbar.
     */
    paginate: number;
    /**
     * Active sorts, in the order the user added them. Omitted while nothing is sorted.
     */
    sortable?: {
        /**
         * Field to sort by — the header cell’s `reference`, if it declares one, otherwise its `field`.
         */
        field: string;
        /**
         * Sort direction.
         */
        direction: 'asc' | 'desc';
    }[];
    /**
     * Active per-column searches. A term search sends `term` (with `exact`); a range search (`between`) sends `min` / `max` instead, either of which may be `null` for an open end. Omitted while nothing is searched.
     */
    searchable?: {
        /**
         * Field to search in.
         */
        field: string;
        /**
         * Search term. Absent on a range search.
         */
        term?: string;
        /**
         * Match the whole value rather than a substring.
         */
        exact?: boolean;
        /**
         * Lower bound of a range search; `null` means unbounded.
         */
        min?: number | string | null;
        /**
         * Upper bound of a range search; `null` means unbounded.
         */
        max?: number | string | null;
    }[];
    /**
     * Active column filters. Omitted while nothing is filtered.
     */
    filterable?: {
        /**
         * Field to filter by.
         */
        field: string;
        /**
         * Values selected in the filter dropdown; the row matches if it equals any of them.
         */
        values: any[];
    }[];
    /**
     * Term from the toolbar’s global search box, covering the fields listed in `header.settings.searchableItems`. Omitted while the box is empty.
     */
    globalSearch?: string;
    /**
     * Ids of the rows currently selected. Attached at request time only, and omitted when the selection is empty — changing the selection does not itself trigger a fetch.
     */
    selected?: (string | number)[];
}

// ── schema/bundled/aura-error-report.bundle.json ──

/**
 * ECS severity level.
 */
export type ErrorSeverity = 'critical' | 'error' | 'warning' | 'info' | 'debug';
/**
 * Error category. `validation` is a schema violation in the config or in the API response, `api` a failed request, `client` a wiring mistake in the host application.
 */
export type ErrorType =
    | 'validation'
    | 'network'
    | 'authentication'
    | 'authorization'
    | 'not_found'
    | 'server'
    | 'client'
    | 'api'
    | 'unknown';

/**
 * What Aura POSTs to `errorReportingEndpoint` while `errorReporting` is on: one batch of ECS-shaped entries, sent with `Content-Type: application/json` and — only when `errorReportingApiKey` is set — an `Authorization: Bearer …` header. Nothing else is sent: no `Accept`, no `X-Requested-With`, no CSRF token, and no wrapper field beside `errors`. The client is native `fetch`, so a same-origin request carries the session cookie and a cross-origin one does not. A batch holds between 1 and 100 entries — the flush sends the whole queue, not `batchSize` of it — and every non-2xx response is retried four times and then re-queued behind an exponential backoff, so an endpoint that rejects a malformed batch will receive it forever.
 */
export interface AuraErrorReport {
    /**
     * The flushed queue, oldest first. Never empty — a flush with nothing queued does not happen — and never longer than the client's `maxQueueSize` of 100.
     *
     * @minItems 1
     */
    errors: [ErrorEntry, ...ErrorEntry[]];
}
/**
 * One reported error. `additionalProperties` is open on purpose: a future Aura release may add fields, and a receiver that rejects the batch over one of them would reject it forever.
 */
export interface ErrorEntry {
    severity: ErrorSeverity;
    /**
     * Copy of `severity`, kept for ECS compatibility. Aura marks it `@deprecated` and always fills it in; a receiver should read `severity`.
     */
    level: 'critical' | 'error' | 'warning' | 'info' | 'debug';
    /**
     * ISO 8601 timestamp of the **first** occurrence. Once the error repeats, `lastTimestamp` marks the most recent one.
     */
    timestamp: string;
    /**
     * Where the error came from — a validator name (`HeaderValidator`, `BodyValidator`, …), a store (`ApiResourcesStore`, `CoreStore`), or a component (`DestroyModal`).
     */
    component: string;
    /**
     * The operation that failed — `validate`, `fetchData`, `resolve`, `report`, …
     */
    action: string;
    type: ErrorType;
    /**
     * Text written for the end user. It is translated through `labels`, so it is **not** a stable identifier — group on `key` instead.
     */
    message: string;
    /**
     * Stable identifier of the error. Validators put the offending field name here; otherwise the store generates `component.action.type`. This is the field to group and deduplicate on.
     */
    key?: string;
    /**
     * Raw developer-facing text — a Zod issue path, an axios message. May contain a URL with its query string.
     */
    details?: string;
    /**
     * Free-form context. A schema violation carries `receivedValue` (the rejected value **verbatim**, which for `HeaderValidator` / `BodyValidator` is the whole response section) and `receivedType`; a failed request carries `kind`, `status` and `code`. Unbounded on the client — a receiver must cap it itself.
     */
    metadata?: {
        [k: string]: any;
    };
    /**
     * Occurrences merged into this entry. **Absent while the error happened once**, so the count is `count ?? 1`.
     */
    count?: number;
    /**
     * ISO 8601 timestamp of the most recent occurrence. Absent until the error repeats.
     */
    lastTimestamp?: string;
    /**
     * Caller-supplied identifier. Aura never fills this in; it can only come from the host application's own `addError` call.
     */
    id?: string;
    /**
     * Stack trace. Aura never fills this in either.
     */
    stack?: string;
    [k: string]: any;
}
