/**
 * Inlines `schema/*.json` and `contract.json` into `src/schemas.generated.ts`.
 *
 * The JSON files under `schema/` are the source of truth — this script only
 * makes them importable from TypeScript without JSON import attributes, which
 * are still uneven across bundlers and Node versions.
 *
 * `node scripts/generate-schemas.mjs`         rewrites the generated file
 * `node scripts/generate-schemas.mjs --check` fails if it is out of date
 */
import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = join(repoRoot, 'src', 'schemas.generated.ts');

/**
 * Maps every schema file to the identifier it is exported under.
 *
 * Kept explicit rather than derived from the filename so a new schema is a
 * deliberate, reviewable addition to the public surface.
 */
const EXPORTS = [
    ['auraErrorReportSchema', 'schema/aura-error-report.schema.json'],
    ['auraRequestSchema', 'schema/aura-request.schema.json'],
    ['auraResponseSchema', 'schema/aura-response.schema.json'],
    ['commonSchema', 'schema/common.schema.json'],
    ['headerSchema', 'schema/header.schema.json'],
    ['bodySchema', 'schema/body.schema.json'],
    ['footerSchema', 'schema/footer.schema.json'],
    ['paginationSchema', 'schema/pagination.schema.json'],
    ['badgeSchema', 'schema/column-configs/badge.schema.json'],
    ['buttonSchema', 'schema/column-configs/button.schema.json'],
    ['customSchema', 'schema/column-configs/custom.schema.json'],
    ['iconSchema', 'schema/column-configs/icon.schema.json'],
    ['linkSchema', 'schema/column-configs/link.schema.json'],
    ['modalSchema', 'schema/column-configs/modal.schema.json'],
    ['progressSchema', 'schema/column-configs/progress.schema.json'],
    ['referenceSchema', 'schema/column-configs/reference.schema.json'],
    ['staticSchema', 'schema/column-configs/static.schema.json'],
];

/**
 * Reads and re-serialises one JSON file at a fixed indent.
 *
 * @param relativePath - Path relative to the repository root.
 * @returns The parsed value and its canonical 4-space serialisation.
 */
async function load(relativePath) {
    const parsed = JSON.parse(await readFile(join(repoRoot, relativePath), 'utf8'));

    return { parsed, source: JSON.stringify(parsed, null, 4) };
}

/**
 * Builds the whole generated module.
 *
 * @returns The TypeScript source to write.
 */
async function build() {
    const manifest = await load('contract.json');

    const blocks = [];
    for (const [identifier, relativePath] of EXPORTS) {
        const { source } = await load(relativePath);
        blocks.push(
            `/** \`${relativePath}\` — see the file for the full description. */\n` +
                `export const ${identifier}: AuraSchemaDocument = ${source};`
        );
    }

    return `/* eslint-disable */
// Generated by scripts/generate-schemas.mjs — do not edit.
// Source of truth: schema/*.json and contract.json. Run \`npm run schemas:generate\`.

/**
 * A JSON Schema document of the Aura contract.
 *
 * Only the keywords this package reads are typed; the rest of the document is
 * left open, because a schema is data to be handed to a validator, not a shape
 * to be walked field by field.
 */
export interface AuraSchemaDocument {
    readonly $schema: string;
    readonly $id: string;
    readonly title?: string;
    readonly description?: string;
    readonly [keyword: string]: unknown;
}

/**
 * The contract manifest — version, dialect, base URI and the file list.
 */
export interface AuraContractManifest {
    readonly version: string;
    readonly dialect: string;
    readonly baseUri: string;
    readonly entrypoints: Readonly<Record<string, string>>;
    readonly bundles: Readonly<Record<string, string>>;
    readonly schemas: readonly string[];
    readonly examples: Readonly<Record<string, string>>;
}

/** \`contract.json\` — the manifest both packagings read. */
export const auraContractManifest: AuraContractManifest = ${manifest.source};

${blocks.join('\n\n')}
`;
}

const generated = await build();

if (process.argv.includes('--check')) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== generated) {
        console.error(
            'src/schemas.generated.ts is out of date with schema/*.json.\n' +
                'Run `npm run schemas:generate` and commit the result.'
        );
        process.exit(1);
    }
    console.log('src/schemas.generated.ts is up to date.');
} else {
    await writeFile(outputPath, generated, 'utf8');
    console.log(`Wrote ${outputPath}`);
}
