/**
 * Generates TypeScript payload types from the contract entrypoints.
 *
 * These describe the *payloads* (`AuraResponse`, `AuraRequest`), not the schema
 * documents — that is what a TypeScript consumer of the contract actually
 * wants. The JSON files stay the source of truth; this output is committed so
 * consumers need no build step, and CI runs `--check` to catch drift.
 *
 * `node scripts/generate-types.mjs`         rewrites src/types/contract.ts
 * `node scripts/generate-types.mjs --check` fails if it is out of date
 */
import { readFile, writeFile, mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { compileFromFile } from 'json-schema-to-typescript';

const repoRoot = join(dirname(fileURLToPath(import.meta.url)), '..');
const outputPath = join(repoRoot, 'src', 'types', 'contract.ts');

const ENTRYPOINTS = [
    ['AuraResponse', 'schema/bundled/aura-response.bundle.json'],
    ['AuraRequest', 'schema/bundled/aura-request.bundle.json'],
    ['AuraErrorReport', 'schema/bundled/aura-error-report.bundle.json'],
];

/**
 * Compiles one entrypoint schema to TypeScript.
 *
 * @param typeName - Name for the root interface.
 * @param relativePath - Schema path relative to the repository root.
 * @returns The compiled declarations, without a banner.
 */
async function compile(typeName, relativePath) {
    return compileFromFile(join(repoRoot, relativePath), {
        cwd: dirname(join(repoRoot, relativePath)),
        bannerComment: '',
        declareExternallyReferenced: true,
        enableConstEnums: false,
        unknownAny: false,
        style: {
            singleQuote: true,
            tabWidth: 4,
            printWidth: 100,
            semi: true,
        },
        customName: (schema, keyNameFromDefinition) =>
            typeof schema.$id === 'string' && schema.$id.endsWith('.bundle.json')
                ? typeName
                : keyNameFromDefinition,
    });
}

const parts = [];
for (const [typeName, relativePath] of ENTRYPOINTS) {
    parts.push(`// ── ${relativePath} ──\n\n${(await compile(typeName, relativePath)).trim()}`);
}

const generated = `/* eslint-disable */
// Generated by scripts/generate-types.mjs — do not edit.
// Source of truth: schema/*.json. Run \`npm run types:generate\`.

${parts.join('\n\n')}
`;

if (process.argv.includes('--check')) {
    const current = await readFile(outputPath, 'utf8').catch(() => '');
    if (current !== generated) {
        console.error(
            'src/types/contract.ts is out of date with schema/*.json.\n' +
                'Run `npm run types:generate` and commit the result.'
        );
        process.exit(1);
    }
    console.log('src/types/contract.ts is up to date.');
} else {
    await mkdir(dirname(outputPath), { recursive: true });
    await writeFile(outputPath, generated, 'utf8');
    console.log(`Wrote ${outputPath}`);
}
